apiVersion: v1
kind: Service
metadata:
  name: cloud-quest-service
spec:
  selector:
    app: cloud-quest-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 3000  # Internal container port
  type: LoadBalancer
